export enum EScopes {
  SUDO = '*',
  READ_SCOPE = '{ORG_SLUG}.SCOPE.READ',
  SUDO_EMPLOYEES = '{ORG_SLUG}.EMPLOYEES.*',
  READ_EMPLOYEES = '{ORG_SLUG}.EMPLOYEES.READ',
  CREATE_EMPLOYEES = '{ORG_SLUG}.EMPLOYEES.CREATE',
  DELETE_EMPLOYEES = '{ORG_SLUG}.EMPLOYEES.DELETE',
  EDIT_EMPLOYEES = '{ORG_SLUG}.EMPLOYEES.EDIT',
  SUDO_ROLE = '{ORG_SLUG}.ROLE.*',
  READ_ROLE = '{ORG_SLUG}.ROLE.READ',
  CREATE_ROLE = '{ORG_SLUG}.ROLE.CREATE',
  DELETE_ROLE = '{ORG_SLUG}.ROLE.DELETE',
  EDIT_ROLE = '{ORG_SLUG}.ROLE.EDIT',
  SUDO_NEWS_ARTICLE = '{ORG_SLUG}.NEWS_ARTICLE.*',
  READ_NEWS_ARTICLE = '{ORG_SLUG}.NEWS_ARTICLE.READ',
  CREATE_NEWS_ARTICLE = '{ORG_SLUG}.NEWS_ARTICLE.CREATE',
  DELETE_NEWS_ARTICLE = '{ORG_SLUG}.NEWS_ARTICLE.DELETE',
  EDIT_NEWS_ARTICLE = '{ORG_SLUG}.NEWS_ARTICLE.EDIT',
  SUDO_NEWSPAPER_CONTENT = '{ORG_SLUG}.NEWSPAPER_CONTENT.*',
  READ_NEWSPAPER_CONTENT = '{ORG_SLUG}.NEWSPAPER_CONTENT.READ',
  CREATE_NEWSPAPER_CONTENT = '{ORG_SLUG}.NEWSPAPER_CONTENT.CREATE',
  DELETE_NEWSPAPER_CONTENT = '{ORG_SLUG}.NEWSPAPER_CONTENT.DELETE',
  EDIT_NEWSPAPER_CONTENT = '{ORG_SLUG}.NEWSPAPER_CONTENT.EDIT',
  SUDO_AD_SLOTS = '{ORG_SLUG}.AD_SLOTS.*',
  READ_AD_SLOTS = '{ORG_SLUG}.AD_SLOTS.READ',
  CREATE_AD_SLOTS = '{ORG_SLUG}.AD_SLOTS.CREATE',
  DELETE_AD_SLOTS = '{ORG_SLUG}.AD_SLOTS.DELETE',
  EDIT_AD_SLOTS = '{ORG_SLUG}.AD_SLOTS.EDIT',
  SUDO_CAMPAIGN = '{ORG_SLUG}.CAMPAIGN.*',
  READ_CAMPAIGN = '{ORG_SLUG}.CAMPAIGN.READ',
  EDIT_CAMPAIGN = '{ORG_SLUG}.CAMPAIGN.EDIT',
  CREATE_CAMPAIGN = '{ORG_SLUG}.CAMPAIGN.CREATE',
  DELETE_CAMPAIGN = '{ORG_SLUG}.CAMPAIGN.DELETE',
  SUDO_AD_CREATIVES = '{ORG_SLUG}.AD_CREATIVES.*',
  READ_AD_CREATIVES = '{ORG_SLUG}.AD_CREATIVES.READ',
  EDIT_AD_CREATIVES = '{ORG_SLUG}.AD_CREATIVES.EDIT',
  CREATE_AD_CREATIVES = '{ORG_SLUG}.AD_CREATIVES.CREATE',
  DELETE_AD_CREATIVES = '{ORG_SLUG}.AD_CREATIVES.DELETE',

  READ_PAYMENT = '{ORG_SLUG}.READ_PAYMENT',
}

export const editorScopes: EScopes[] = [
  EScopes.SUDO_NEWSPAPER_CONTENT,
  EScopes.EDIT_NEWS_ARTICLE,
  EScopes.READ_NEWS_ARTICLE,
  EScopes.READ_AD_CREATIVES,
];
export const advertisingScopes: EScopes[] = [
  EScopes.READ_AD_SLOTS,
  EScopes.SUDO_CAMPAIGN,
];

export const designScopes: EScopes[] = [EScopes.SUDO_AD_CREATIVES];

export const financeScopes: EScopes[] = [EScopes.READ_PAYMENT];

export const adminScopes: EScopes[] = [EScopes.SUDO];
